#!/bin/bash

TARGET=main.native
INCLUDE_DIRS=lib

function clean
{
	ocamlbuild -clean
	exit 0
}

while [ $# -ne 0 ] && [ ! -z $1 ]; do
	case $1 in
		debug|clean|rebuild) "$1" ;;
		*) echo "build: invalid argument $1" && exit 1 ;;
	esac
	shift
done


time ocamlbuild $TARGET -use-ocamlfind -Is $INCLUDE_DIRS
